version: "3.8"
services:
  demo:
    build:
      context: .
      dockerfile: ./docker/demo.Dockerfile
    image: lbovolini/demo
    ports:
      - "8080:8081"
    environment:
      SERVER_PORT: 8081
      APP_DB_HOSTNAME: toxiproxy
      APP_DB_PORT: 25555
      APP_DB_NAME: master
      APP_DB_USERNAME: sa
      APP_DB_PASSWORD: myPassword
      time: 200
    depends_on:
      demo-sybase:
        condition: service_healthy
    restart: on-failure
    networks:
      - demo-network

  demo-mysql:
    image: mysql:8.0.28-debian
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      interval: 5s
    networks:
      - demo-network

  demo-sybase:
    image: ingleivj/sybase16
    ports:
      - "5000:5000"
    healthcheck:
      test: /bin/bash -c "source /opt/sybase/SYBASE.sh; isql -U sa -P myPassword -S MYSYBASE -v"
      interval: 5s
    networks:
      - demo-network

  toxiproxy:
    image: shopify/toxiproxy:2.1.4
    networks:
      - demo-network
    ports:
      - "8474:8474"
      - "19385:19385"
      - "25555:25555"
volumes:
  mysql-volume:

networks:
  demo-network: