version: "3.8"
services:
  demo:
    build:
      context: .
      dockerfile: ./docker/demo.Dockerfile
    image: lbovolini/demo
    ports:
      - "8080:8081"
    environment:
      SERVER_PORT: 8081
      APP_DB_HOSTNAME: toxiproxy
      APP_DB_PORT: 19385
      APP_DB_NAME: demo
      APP_DB_USERNAME: demo
      APP_DB_PASSWORD: demo
      APP_CACHE_HOSTNAME: demo-redis
      APP_CACHE_PORT: 6379
      time: 200
    depends_on:
      demo-mysql:
        condition: service_healthy
      demo-redis:
        condition: service_healthy
    restart: on-failure
    networks:
      demo-network:
        aliases:
          - demo

  demo-mysql:
    image: mysql:8.0.28-debian
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      interval: 5s
    networks:
      demo-network:
        aliases:
          - demo-mysql

  demo-redis:
    image: redis:6.2.6-bullseye
    ports:
      - "6379:6379"
    volumes:
      - mysql-volume:/var/lib/mysql
    healthcheck:
      test: redis-cli ping
      interval: 5s
    networks:
      demo-network:
        aliases:
          - demo-redis

  toxiproxy:
    image: shopify/toxiproxy:2.1.4
    networks:
      demo-network:
        aliases:
          - toxiproxy
    ports:
      - "8474:8474"
      - "19385:19385"
volumes:
  mysql-volume:

networks:
  demo-network: